# Site settings
title: PFactor.io
email: charath@pfactor.io
description: > # this means to ignore newlines until "baseurl:"
  pfactor.io provides tutorials, blog posts and resources for electronics and aviation enthusiasts.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://pfactor.io/" # the base hostname & protocol for your site
#url: "http://localhost:4000/"
twitter_username: pfactorio
github_username:  pfactorio
facebook_page: https://www.facebook.com/pfactor.io/
disqus_shortname: pfactorio
sass:
  style: compressed
plugins:
  - jekyll-seo-tag

# Build settings
markdown: kramdown
permalink: /:categories/:title/
# include: ['_posts/lessons']
highlighter: rouge

redcarpet:
  extensions: [tables]

exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]
